CL_DSW/CL_DSW_CARRITO/CL_DSW_CARRITO/Models/PRODUCTO.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CL_DSW_CARRITO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCTO()
        {
            this.DETALLEBOLETA = new HashSet<DETALLEBOLETA>();
        }
    
        public int IDE_PRO { get; set; }
        public string DES_PRO { get; set; }
        public int IDE_CAT { get; set; }
        public decimal PRE_PRO { get; set; }
        public int STO_PRO { get; set; }
        public string IMG_PRO { get; set; }
    
        public virtual CATEGORIA CATEGORIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLEBOLETA> DETALLEBOLETA { get; set; }
    }
}

CL_DSW/CL_DSW_CARRITO/CL_DSW_CARRITO/Controllers/CarritoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using CL_DSW_CARRITO.Models;

namespace CL_DSW_CARRITO.Controllers
{
    public class CarritoController : Controller
    {
        FUENTESODAEntities fe = new FUENTESODAEntities();

        private int getIndex(int id)
        {
            List<CarritoItem> compra = (List<CarritoItem>)Session["carrito"];
            for (int i = 0; i < compra.Count; i++)
            {
                if (compra[i].Producto.IDE_PRO == id)
                {
                    return i;
                }
            }
            return -1;
        }
        [HttpPost]
        public JsonResult AgregarCarrito(int id, int cantidad)
        {
            if (Session["carrito"] == null)
            {
                List<CarritoItem> compra = new List<CarritoItem>();
                compra.Add(new CarritoItem(fe.PRODUCTO.Find(id), cantidad));
                Session["carrito"] = compra;
            }
            else
            {
                List<CarritoItem> compra = (List<CarritoItem>)Session["carrito"];
                int IndexExistente = getIndex(id);
                if (IndexExistente == -1)
                {
                    compra.Add(new CarritoItem(fe.PRODUCTO.Find(id), cantidad));
                }
                else
                {
                    compra[IndexExistente].Cantidad += cantidad;
                }
                Session["carrito"] = compra;
            }
            return Json(new { Response = true}, JsonRequestBehavior.AllowGet);
        }

        public ActionResult AgregarCarrito()
        {
            return View();
        }

        public ActionResult Eliminar(int id)
        {
            List<CarritoItem> compra = (List<CarritoItem>)Session["carrito"];
            compra.RemoveAt(getIndex(id));
            return View("AgregarCarrito");
        }

        public ActionResult FinalizarCompra()
        {
            List<CarritoItem> compra = (List<CarritoItem>)Session["carrito"];
            if (compra != null && compra.Count > 0)
            {
                BOLETA nuevaBoleta = new BOLETA();
                nuevaBoleta.FEC_BOL = DateTime.Now;
                nuevaBoleta.IDE_CLI = Convert.ToInt32(Session["Cliente"]);
                nuevaBoleta.IDE_VEN = Convert.ToInt32(Session["Vendedor"]);
                nuevaBoleta.DETALLEBOLETA = (from producto in compra
                                        select new DETALLEBOLETA
                                        {
                                            IDE_PRO = producto.Producto.IDE_PRO,
                                            CAN_ART = producto.Cantidad,

                                        }).ToList();
                fe.BOLETA.Add(nuevaBoleta);
                fe.SaveChanges();
                Session["carrito"] = new List<CarritoItem>();
                Session["Cliente"] = null;
                Session["Vendedor"] = null;
                Session.Remove("Cliente");
                Session.Remove("Vendedor");
            }
            return View();
        }
    }
}

CL_DSW/CL_DSW_CARRITO/CL_DSW_CARRITO/Controllers/ProductoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using CL_DSW_CARRITO.Models;

namespace CL_DSW_CARRITO.Controllers
{
    public class ProductoController : Controller
    {
        FUENTESODAEntities fe = new FUENTESODAEntities();
        // GET: Producto
        public ActionResult Producto()
        {
            return View(fe.PRODUCTO.ToList());
        }
    }
}

CL_DSW/CL_DSW_CARRITO/CL_DSW_CARRITO/Views/Producto/Producto.cshtml
@model IEnumerable<CL_DSW_CARRITO.Models.PRODUCTO>

@{
    ViewBag.Title = "Producto";
}


<div class="container">
    <h3>Seleccionar un Producto</h3>
    <div class="row">
        @foreach (var item in Model)
        {
            <div class="site_product">
                <div class="row">
                    <div class="img_product">
                        <img src="../@item.IMG_PRO" alt="">
                    </div>
                    <div class="info_product">
                        <div class="codigo">
                            <b>Codigo :</b><span class="id_codigo"> @item.IDE_PRO</span>
                        </div>
                        <div class="descripcion">
                            <span class="nombre_pro">
                                <b>Nombre :</b> @item.DES_PRO
                            </span>
                            <span class="categoria_pro">
                                <b>Categoria :</b> @item.CATEGORIA.DES_CAT
                            </span>
                            <span class="Precio">
                                <b>Precio :</b> @String.Format("{0:C}", item.PRE_PRO)
                            </span>
                            <span class="Stock">
                                <b>Stock :</b> @item.STO_PRO
                            </span>
                        </div>
                    </div>
                </div>
                <div class="accion_product">
                    <div class="cantidad_pro">
                        <label for="">Ingrese Cantidad</label>
                        <input type="number" class="cantidad" name="" id="   ">
                    </div>
                    <div class="btn_ordenar">
                        <a href="#" class="ordenar">Ordenar</a>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

<script>

    $(function () {
        $(".ordenar").on("click", function (event) {
            event.preventDefault();
            var ProductoId = $(this).parent().parent().parent().find(".id_codigo").text();
            var cantidad = $(this).parent().parent().find(".cantidad").val();
            console.log(ProductoId + "-" + cantidad);
            $.ajax({
                url: "@Url.Action("AgregarCarrito", "Carrito")",
                data: { id : ProductoId, cantidad: cantidad },
                type: "post",
                success: function (respose) {
                    window.location.href = "@Url.Action("AgregarCarrito", "Carrito")";
                },
                error: function (err, error) {
                    alert(error);
                }
            });
        });
        $(".numbers").keydown(function (e) {
            if ($.inArray(e.keyCode, [46, 8, 9, 27, 13, 40]) != -1
                (e.keyCode == 65 && e.ctrlKey === true) ||
                (e - keyCode >= 35 && e.keyCode <= 39)) {
                return;
            }
            if ((e.shiftKey || (e.keyCode < 48 || e.keyCode > 57)) && (e.keyCode < 96 || e.keyCode > 105)) {
                e.preventDefault();
            }
        });
    });
</script>